steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/whatsapp-crm', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/whatsapp-crm']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'whatsapp-crm'
      - '--image'
      - 'gcr.io/$PROJECT_ID/whatsapp-crm'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'FLASK_ENV=production,PROJECT_ID=${PROJECT_ID},REGION=${_REGION},WAHA_API_URL=${_WAHA_API_URL},WAHA_DEFAULT_SESSION=${_WAHA_DEFAULT_SESSION},SECRET_KEY=${_SECRET_KEY},POCKETBASE_URL=${_POCKETBASE_URL},PUBLIC_GOLD_URL=${_PUBLIC_GOLD_URL}'

images:
  - 'gcr.io/$PROJECT_ID/whatsapp-crm'

substitutions:
  _REGION: asia-southeast1
  _WAHA_API_URL: https://my-app-352501285879.asia-southeast1.run.app
  _WAHA_DEFAULT_SESSION: session
  _POCKETBASE_URL: https://hamirulhafizal.pockethost.io
  _PUBLIC_GOLD_URL: https://publicgold.com.my/ 